apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  namespace: prod
spec:
  replicas: 1
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      containers:
        - name: gateway
          image: "559543475782.dkr.ecr.ap-northeast-2.amazonaws.com/o-o-backend:gateway-latest"
          imagePullPolicy: Always
          ports: [{ containerPort: 8080 }]
          resources:
            requests: { cpu: "150m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: gateway-config
            - secretRef:
                name: gateway-secret
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: prod
spec:
  type: NodePort
  selector: { app: gateway }
  ports:
    - name: http
      port: 80
      targetPort: 8080
