apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-deploy
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector: { matchLabels: { app: trend } }
  template:
    metadata: { labels: { app: trend } }
    spec:
      containers:
        - name: trend
          image: "559543475782.dkr.ecr.ap-northeast-2.amazonaws.com/o-o-backend:trend-service-latest"
          imagePullPolicy: Always
          ports: [{ containerPort: 8085 }]
          resources:
            requests: { cpu: "150m", memory: "256Mi" }
            limits:   { cpu: "400m", memory: "512Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8085 }
            initialDelaySeconds: 25
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6          # (선택) 일시적 지연 완충
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8085 }
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet: { path: /actuator/health, port: 8085 }
            periodSeconds: 3
            failureThreshold: 60         # 최대 ~180초(3분)까지 기동 허용
            timeoutSeconds: 2
#          envFrom:
#            - configMapRef:
#                name: trend-config
#            - secretRef:
#                name: trend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: trend-svc
  namespace: prod
spec:
  type: ClusterIP
  selector: { app: trend }
  ports:
    - name: http
      port: 8085
      targetPort: 8085
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trend-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trend-deploy
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60