apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: prod
spec:
  replicas: 1
  selector: { matchLabels: { app: user } }
  template:
    metadata: { labels: { app: user } }
    spec:
      containers:
        - name: user
          image: "559543475782.dkr.ecr.ap-northeast-2.amazonaws.com/o-o-backend:user-initial"
          ports: [{ containerPort: 8081 }]
          resources:
            requests: { cpu: "150m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8081 }
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: user-config
            - secretRef:
                name: user-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: prod
spec:
  type: ClusterIP
  selector: { app: user }
  ports:
    - name: http
      port: 8081
      targetPort: 8081
