apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: o-o-alb
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:559543475782:certificate/680fa8a6-5ad1-4cc2-b9ba-3867f36b840b
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: api.o-o.io.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-svc
                port:
                  number: 80
